export * from './ArrowLeft';
export * from './ArrowRight';
export * from './ArrowTopRight';
export * from './SquareCheck';
export * from './TriangleUp';
export * from './TriangleDown';
export * from './BachelorCap';
export * from './FileChart';
export * from './PeoplePlus';
